ALTER TABLE product_question
  ADD COLUMN IF NOT EXISTS question_likes INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS question_dislikes INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS answer_likes INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS answer_dislikes INTEGER DEFAULT 0;
